// Formula library — categorised, searchable, click-to-insert. Every entry must:
//   • have a unique id (used for MRU bookkeeping and as autocomplete trigger)
//   • render via KaTeX (no MathLive-only syntax)
//   • carry a non-empty `keywords` string for fuzzy search
//   • belong to exactly one category from FORMULA_CATEGORIES
// A `level` field (beginner | intermediate | advanced) is assigned automatically
// at load time by inferLevel() below — override per-entry if the heuristic gets
// it wrong by adding a `level` property explicitly.
//
// Adding entries: append to FORMULAS — order within a category controls display order.
window.FORMULA_CATEGORIES = [
  { id: "algebra",     label: "Algebra" },
  { id: "trig",        label: "Trigonometry" },
  { id: "calculus",    label: "Calculus" },
  { id: "linalg",      label: "Linear Algebra" },
  { id: "geometry",    label: "Geometry" },
  { id: "stats",       label: "Statistics" },
  { id: "discrete",    label: "Discrete & Number" },
  { id: "mechanics",   label: "Mechanics" },
  { id: "em",          label: "Electromagnetism" },
  { id: "thermo",      label: "Thermodynamics" },
  { id: "quantum",     label: "Quantum" },
  { id: "relativity",  label: "Relativity" },
  { id: "optics",      label: "Optics & Waves" },
  { id: "chemistry",   label: "Chemistry" },
  { id: "engineering", label: "Engineering" },
  { id: "constants",   label: "Constants" },
];

window.FORMULAS = [
  // ── Algebra ──────────────────────────────────────────────────────────────
  { id: "qform", category: "algebra", name: "Quadratic formula",
    latex: "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
    notes: "Solves ax² + bx + c = 0", keywords: "quadratic roots polynomial solve" },
  { id: "discriminant", category: "algebra", name: "Discriminant",
    latex: "\\Delta = b^2 - 4ac",
    notes: "Sign tells how many real roots", keywords: "discriminant delta roots" },
  { id: "diffsqr", category: "algebra", name: "Difference of squares",
    latex: "a^2 - b^2 = (a-b)(a+b)",
    keywords: "difference squares factoring" },
  { id: "sumcube", category: "algebra", name: "Sum of cubes",
    latex: "a^3 + b^3 = (a+b)(a^2 - ab + b^2)",
    keywords: "sum cubes factoring" },
  { id: "diffcube", category: "algebra", name: "Difference of cubes",
    latex: "a^3 - b^3 = (a-b)(a^2 + ab + b^2)",
    keywords: "difference cubes factoring" },
  { id: "binomial", category: "algebra", name: "Binomial theorem",
    latex: "(x+y)^n = \\sum_{k=0}^{n} \\binom{n}{k} x^{n-k} y^k",
    keywords: "binomial expansion pascal" },
  { id: "binom_coef", category: "algebra", name: "Binomial coefficient",
    latex: "\\binom{n}{k} = \\frac{n!}{k!(n-k)!}",
    keywords: "binomial choose combination" },
  { id: "geom_series_finite", category: "algebra", name: "Geometric series (finite)",
    latex: "\\sum_{k=0}^{n-1} ar^k = a\\,\\frac{1-r^n}{1-r}",
    keywords: "geometric series sum partial" },
  { id: "geom_series_inf", category: "algebra", name: "Geometric series (infinite, |r|<1)",
    latex: "\\sum_{k=0}^{\\infty} ar^k = \\frac{a}{1-r}",
    keywords: "geometric series sum convergent infinite" },
  { id: "arith_sum", category: "algebra", name: "Arithmetic series",
    latex: "S_n = \\frac{n}{2}(2a + (n-1)d) = \\frac{n(a + a_n)}{2}",
    keywords: "arithmetic progression sum" },
  { id: "sum_n", category: "algebra", name: "Sum of first n integers",
    latex: "\\sum_{k=1}^{n} k = \\frac{n(n+1)}{2}",
    keywords: "sum integers triangular" },
  { id: "sum_squares", category: "algebra", name: "Sum of squares",
    latex: "\\sum_{k=1}^{n} k^2 = \\frac{n(n+1)(2n+1)}{6}",
    keywords: "sum squares" },
  { id: "sum_cubes", category: "algebra", name: "Sum of cubes",
    latex: "\\sum_{k=1}^{n} k^3 = \\left(\\frac{n(n+1)}{2}\\right)^2",
    keywords: "sum cubes" },
  { id: "logprod", category: "algebra", name: "Log of product",
    latex: "\\log(xy) = \\log x + \\log y",
    keywords: "logarithm product rule" },
  { id: "logquot", category: "algebra", name: "Log of quotient",
    latex: "\\log\\!\\left(\\tfrac{x}{y}\\right) = \\log x - \\log y",
    keywords: "logarithm quotient rule" },
  { id: "logpow", category: "algebra", name: "Log of power",
    latex: "\\log(x^n) = n\\log x",
    keywords: "logarithm power rule" },
  { id: "logchange", category: "algebra", name: "Change of base",
    latex: "\\log_b x = \\frac{\\log_a x}{\\log_a b}",
    keywords: "logarithm change base" },
  { id: "expsum", category: "algebra", name: "Exponential of sum",
    latex: "e^{x+y} = e^x \\cdot e^y",
    keywords: "exponential sum" },
  { id: "absineq", category: "algebra", name: "Triangle inequality",
    latex: "|a + b| \\le |a| + |b|",
    keywords: "triangle inequality absolute value" },
  { id: "amgm", category: "algebra", name: "AM–GM inequality",
    latex: "\\frac{x_1 + \\dots + x_n}{n} \\ge \\sqrt[n]{x_1 \\cdots x_n}",
    keywords: "arithmetic geometric mean inequality" },
  { id: "cauchy_schwarz", category: "algebra", name: "Cauchy–Schwarz inequality",
    latex: "\\left(\\sum_i a_i b_i\\right)^{\\!2} \\le \\left(\\sum_i a_i^2\\right)\\!\\left(\\sum_i b_i^2\\right)",
    keywords: "cauchy schwarz inequality" },
  { id: "complex_conj", category: "algebra", name: "Complex conjugate product",
    latex: "z\\bar{z} = |z|^2",
    keywords: "complex conjugate modulus" },
  { id: "euler_id", category: "algebra", name: "Euler's identity",
    latex: "e^{i\\pi} + 1 = 0",
    keywords: "euler identity beautiful" },
  { id: "euler_form", category: "algebra", name: "Euler's formula",
    latex: "e^{i\\theta} = \\cos\\theta + i\\sin\\theta",
    keywords: "euler complex exponential" },
  { id: "demoivre", category: "algebra", name: "De Moivre's theorem",
    latex: "(\\cos\\theta + i\\sin\\theta)^n = \\cos(n\\theta) + i\\sin(n\\theta)",
    keywords: "de moivre complex power" },

  // ── Trigonometry ─────────────────────────────────────────────────────────
  { id: "pyth_id", category: "trig", name: "Pythagorean identity",
    latex: "\\sin^2\\theta + \\cos^2\\theta = 1",
    keywords: "pythagorean identity sin cos" },
  { id: "pyth_id2", category: "trig", name: "Pythagorean identity (tan)",
    latex: "1 + \\tan^2\\theta = \\sec^2\\theta",
    keywords: "pythagorean tangent secant" },
  { id: "pyth_id3", category: "trig", name: "Pythagorean identity (cot)",
    latex: "1 + \\cot^2\\theta = \\csc^2\\theta",
    keywords: "pythagorean cotangent cosecant" },
  { id: "sinsum", category: "trig", name: "Sine of sum",
    latex: "\\sin(\\alpha \\pm \\beta) = \\sin\\alpha\\cos\\beta \\pm \\cos\\alpha\\sin\\beta",
    keywords: "sine sum difference angle" },
  { id: "cossum", category: "trig", name: "Cosine of sum",
    latex: "\\cos(\\alpha \\pm \\beta) = \\cos\\alpha\\cos\\beta \\mp \\sin\\alpha\\sin\\beta",
    keywords: "cosine sum difference angle" },
  { id: "tansum", category: "trig", name: "Tangent of sum",
    latex: "\\tan(\\alpha \\pm \\beta) = \\frac{\\tan\\alpha \\pm \\tan\\beta}{1 \\mp \\tan\\alpha\\tan\\beta}",
    keywords: "tangent sum difference angle" },
  { id: "doubsin", category: "trig", name: "Double-angle sine",
    latex: "\\sin(2\\theta) = 2\\sin\\theta\\cos\\theta",
    keywords: "double angle sine" },
  { id: "doubcos", category: "trig", name: "Double-angle cosine",
    latex: "\\cos(2\\theta) = \\cos^2\\theta - \\sin^2\\theta = 2\\cos^2\\theta - 1 = 1 - 2\\sin^2\\theta",
    keywords: "double angle cosine" },
  { id: "doubtan", category: "trig", name: "Double-angle tangent",
    latex: "\\tan(2\\theta) = \\frac{2\\tan\\theta}{1 - \\tan^2\\theta}",
    keywords: "double angle tangent" },
  { id: "halfsin", category: "trig", name: "Half-angle sine",
    latex: "\\sin\\!\\left(\\tfrac{\\theta}{2}\\right) = \\pm\\sqrt{\\tfrac{1-\\cos\\theta}{2}}",
    keywords: "half angle sine" },
  { id: "halfcos", category: "trig", name: "Half-angle cosine",
    latex: "\\cos\\!\\left(\\tfrac{\\theta}{2}\\right) = \\pm\\sqrt{\\tfrac{1+\\cos\\theta}{2}}",
    keywords: "half angle cosine" },
  { id: "prod_to_sum", category: "trig", name: "Product to sum (sin·cos)",
    latex: "\\sin A \\cos B = \\tfrac{1}{2}\\bigl[\\sin(A+B) + \\sin(A-B)\\bigr]",
    keywords: "product sum trig" },
  { id: "sum_to_prod", category: "trig", name: "Sum to product (sin)",
    latex: "\\sin A + \\sin B = 2\\sin\\!\\left(\\tfrac{A+B}{2}\\right)\\cos\\!\\left(\\tfrac{A-B}{2}\\right)",
    keywords: "sum product trig" },
  { id: "law_cosines", category: "trig", name: "Law of cosines",
    latex: "c^2 = a^2 + b^2 - 2ab\\cos C",
    keywords: "law cosines triangle" },
  { id: "law_sines", category: "trig", name: "Law of sines",
    latex: "\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}",
    keywords: "law sines triangle" },
  { id: "tri_area", category: "trig", name: "Triangle area (SAS)",
    latex: "\\text{Area} = \\tfrac{1}{2}ab\\sin C",
    keywords: "triangle area sas" },
  { id: "polar_xy", category: "trig", name: "Polar to Cartesian",
    latex: "x = r\\cos\\theta,\\quad y = r\\sin\\theta",
    keywords: "polar cartesian conversion" },
  { id: "cart_polar", category: "trig", name: "Cartesian to polar",
    latex: "r = \\sqrt{x^2 + y^2},\\quad \\theta = \\arctan\\!\\left(\\tfrac{y}{x}\\right)",
    keywords: "cartesian polar conversion" },
  { id: "deg_rad", category: "trig", name: "Degrees ↔ radians",
    latex: "\\theta_{\\text{rad}} = \\theta_{\\text{deg}} \\cdot \\frac{\\pi}{180}",
    keywords: "degrees radians conversion" },
  { id: "arc_length", category: "trig", name: "Arc length",
    latex: "s = r\\theta",
    keywords: "arc length radian" },

  // ── Calculus ─────────────────────────────────────────────────────────────
  { id: "deriv_def", category: "calculus", name: "Derivative (definition)",
    latex: "f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}",
    keywords: "derivative definition limit difference quotient" },
  { id: "power_rule", category: "calculus", name: "Power rule",
    latex: "\\frac{d}{dx}\\,x^n = n x^{n-1}",
    keywords: "power rule derivative" },
  { id: "product_rule", category: "calculus", name: "Product rule",
    latex: "\\frac{d}{dx}[f(x)g(x)] = f'(x)g(x) + f(x)g'(x)",
    keywords: "product rule derivative" },
  { id: "quotient_rule", category: "calculus", name: "Quotient rule",
    latex: "\\frac{d}{dx}\\!\\left[\\tfrac{f(x)}{g(x)}\\right] = \\frac{f'(x)g(x) - f(x)g'(x)}{g(x)^2}",
    keywords: "quotient rule derivative" },
  { id: "chain_rule", category: "calculus", name: "Chain rule",
    latex: "\\frac{d}{dx}f(g(x)) = f'(g(x))\\,g'(x)",
    keywords: "chain rule composite derivative" },
  { id: "deriv_sin", category: "calculus", name: "Derivative of sin",
    latex: "\\frac{d}{dx}\\sin x = \\cos x",
    keywords: "derivative sine" },
  { id: "deriv_cos", category: "calculus", name: "Derivative of cos",
    latex: "\\frac{d}{dx}\\cos x = -\\sin x",
    keywords: "derivative cosine" },
  { id: "deriv_tan", category: "calculus", name: "Derivative of tan",
    latex: "\\frac{d}{dx}\\tan x = \\sec^2 x",
    keywords: "derivative tangent" },
  { id: "deriv_exp", category: "calculus", name: "Derivative of e^x",
    latex: "\\frac{d}{dx}e^x = e^x",
    keywords: "derivative exponential" },
  { id: "deriv_ln", category: "calculus", name: "Derivative of ln",
    latex: "\\frac{d}{dx}\\ln x = \\frac{1}{x}",
    keywords: "derivative logarithm natural log" },
  { id: "deriv_log", category: "calculus", name: "Derivative of log_b",
    latex: "\\frac{d}{dx}\\log_b x = \\frac{1}{x\\ln b}",
    keywords: "derivative log base" },
  { id: "ftc1", category: "calculus", name: "Fundamental theorem of calculus (I)",
    latex: "\\frac{d}{dx}\\!\\int_a^x f(t)\\,dt = f(x)",
    keywords: "fundamental theorem calculus derivative integral" },
  { id: "ftc2", category: "calculus", name: "Fundamental theorem of calculus (II)",
    latex: "\\int_a^b f(x)\\,dx = F(b) - F(a)",
    keywords: "fundamental theorem calculus evaluation" },
  { id: "intpow", category: "calculus", name: "Integral of x^n",
    latex: "\\int x^n\\,dx = \\frac{x^{n+1}}{n+1} + C, \\quad n \\ne -1",
    keywords: "integral power" },
  { id: "intinv", category: "calculus", name: "Integral of 1/x",
    latex: "\\int \\tfrac{1}{x}\\,dx = \\ln|x| + C",
    keywords: "integral inverse log" },
  { id: "intexp", category: "calculus", name: "Integral of e^x",
    latex: "\\int e^x\\,dx = e^x + C",
    keywords: "integral exponential" },
  { id: "intsin", category: "calculus", name: "Integral of sin",
    latex: "\\int \\sin x\\,dx = -\\cos x + C",
    keywords: "integral sine" },
  { id: "intcos", category: "calculus", name: "Integral of cos",
    latex: "\\int \\cos x\\,dx = \\sin x + C",
    keywords: "integral cosine" },
  { id: "intsec2", category: "calculus", name: "Integral of sec²",
    latex: "\\int \\sec^2 x\\,dx = \\tan x + C",
    keywords: "integral secant squared" },
  { id: "ibp", category: "calculus", name: "Integration by parts",
    latex: "\\int u\\,dv = uv - \\int v\\,du",
    keywords: "integration parts" },
  { id: "usub", category: "calculus", name: "u-substitution",
    latex: "\\int f(g(x))\\,g'(x)\\,dx = \\int f(u)\\,du",
    keywords: "substitution integration u" },
  { id: "taylor", category: "calculus", name: "Taylor series",
    latex: "f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n",
    keywords: "taylor series expansion" },
  { id: "maclaurin", category: "calculus", name: "Maclaurin series",
    latex: "f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(0)}{n!}x^n",
    keywords: "maclaurin series expansion" },
  { id: "ts_exp", category: "calculus", name: "Series for e^x",
    latex: "e^x = \\sum_{n=0}^{\\infty} \\frac{x^n}{n!}",
    keywords: "taylor series exponential" },
  { id: "ts_sin", category: "calculus", name: "Series for sin x",
    latex: "\\sin x = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n+1}}{(2n+1)!}",
    keywords: "taylor series sine" },
  { id: "ts_cos", category: "calculus", name: "Series for cos x",
    latex: "\\cos x = \\sum_{n=0}^{\\infty} \\frac{(-1)^n x^{2n}}{(2n)!}",
    keywords: "taylor series cosine" },
  { id: "ts_geom", category: "calculus", name: "Series for 1/(1-x)",
    latex: "\\frac{1}{1-x} = \\sum_{n=0}^{\\infty} x^n, \\quad |x|<1",
    keywords: "taylor series geometric" },
  { id: "ts_ln", category: "calculus", name: "Series for ln(1+x)",
    latex: "\\ln(1+x) = \\sum_{n=1}^{\\infty} \\frac{(-1)^{n+1} x^n}{n}, \\quad |x|<1",
    keywords: "taylor series logarithm" },
  { id: "lhopital", category: "calculus", name: "L'Hôpital's rule",
    latex: "\\lim_{x \\to a} \\frac{f(x)}{g(x)} = \\lim_{x \\to a} \\frac{f'(x)}{g'(x)}",
    keywords: "lhopital limit indeterminate" },
  { id: "gradient", category: "calculus", name: "Gradient",
    latex: "\\nabla f = \\left(\\tfrac{\\partial f}{\\partial x},\\,\\tfrac{\\partial f}{\\partial y},\\,\\tfrac{\\partial f}{\\partial z}\\right)",
    keywords: "gradient vector calculus" },
  { id: "divergence", category: "calculus", name: "Divergence",
    latex: "\\nabla \\cdot \\vec F = \\tfrac{\\partial F_x}{\\partial x} + \\tfrac{\\partial F_y}{\\partial y} + \\tfrac{\\partial F_z}{\\partial z}",
    keywords: "divergence vector calculus" },
  { id: "curl", category: "calculus", name: "Curl",
    latex: "\\nabla \\times \\vec F = \\left(\\tfrac{\\partial F_z}{\\partial y} - \\tfrac{\\partial F_y}{\\partial z},\\,\\tfrac{\\partial F_x}{\\partial z} - \\tfrac{\\partial F_z}{\\partial x},\\,\\tfrac{\\partial F_y}{\\partial x} - \\tfrac{\\partial F_x}{\\partial y}\\right)",
    keywords: "curl vector calculus" },
  { id: "laplacian", category: "calculus", name: "Laplacian",
    latex: "\\nabla^2 f = \\tfrac{\\partial^2 f}{\\partial x^2} + \\tfrac{\\partial^2 f}{\\partial y^2} + \\tfrac{\\partial^2 f}{\\partial z^2}",
    keywords: "laplacian del squared" },
  { id: "stokes", category: "calculus", name: "Stokes' theorem",
    latex: "\\oint_{\\partial S} \\vec F \\cdot d\\vec r = \\iint_S (\\nabla \\times \\vec F) \\cdot d\\vec S",
    keywords: "stokes theorem" },
  { id: "divthm", category: "calculus", name: "Divergence theorem",
    latex: "\\iiint_V (\\nabla \\cdot \\vec F)\\,dV = \\oiint_{\\partial V} \\vec F \\cdot d\\vec S",
    keywords: "divergence theorem gauss" },
  { id: "green", category: "calculus", name: "Green's theorem",
    latex: "\\oint_{\\partial D}(P\\,dx + Q\\,dy) = \\iint_D \\left(\\tfrac{\\partial Q}{\\partial x} - \\tfrac{\\partial P}{\\partial y}\\right)dA",
    keywords: "green theorem" },

  // ── Linear Algebra ───────────────────────────────────────────────────────
  { id: "mat2", category: "linalg", name: "2×2 Matrix",
    latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}",
    keywords: "matrix two pmatrix array grid" },
  { id: "mat3", category: "linalg", name: "3×3 Matrix",
    latex: "\\begin{pmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{pmatrix}",
    keywords: "matrix three pmatrix array grid" },
  { id: "bmat2", category: "linalg", name: "2×2 Bracket Matrix",
    latex: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}",
    keywords: "matrix bracket bmatrix array grid" },
  { id: "bmat3", category: "linalg", name: "3×3 Bracket Matrix",
    latex: "\\begin{bmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{bmatrix}",
    keywords: "matrix bracket bmatrix array grid" },
  { id: "colvec", category: "linalg", name: "Column Vector (3D)",
    latex: "\\begin{pmatrix} x \\\\ y \\\\ z \\end{pmatrix}",
    keywords: "column vector matrix pmatrix 3d" },
  { id: "identity2", category: "linalg", name: "2×2 Identity Matrix",
    latex: "I_2 = \\begin{pmatrix} 1 & 0 \\\\ 0 & 1 \\end{pmatrix}",
    keywords: "identity matrix two linalg" },
  { id: "identity3", category: "linalg", name: "3×3 Identity Matrix",
    latex: "I_3 = \\begin{pmatrix} 1 & 0 & 0 \\\\ 0 & 1 & 0 \\\\ 0 & 0 & 1 \\end{pmatrix}",
    keywords: "identity matrix three linalg" },
  { id: "det2", category: "linalg", name: "Determinant (2×2)",
    latex: "\\det\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix} = ad - bc",
    keywords: "determinant matrix two" },
  { id: "det3", category: "linalg", name: "Determinant (3×3)",
    latex: "\\det\\!\\begin{pmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{pmatrix} = a(ei - fh) - b(di - fg) + c(dh - eg)",
    keywords: "determinant matrix three" },
  { id: "inv2", category: "linalg", name: "2×2 inverse",
    latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}^{\\!-1} = \\frac{1}{ad-bc}\\begin{pmatrix} d & -b \\\\ -c & a \\end{pmatrix}",
    keywords: "inverse matrix two" },
  { id: "dotprod", category: "linalg", name: "Dot product",
    latex: "\\vec a \\cdot \\vec b = \\sum_i a_i b_i = |\\vec a||\\vec b|\\cos\\theta",
    keywords: "dot product inner" },
  { id: "crossprod", category: "linalg", name: "Cross product (3D)",
    latex: "\\vec a \\times \\vec b = \\det\\begin{pmatrix} \\hat\\imath & \\hat\\jmath & \\hat k \\\\ a_1 & a_2 & a_3 \\\\ b_1 & b_2 & b_3 \\end{pmatrix}",
    keywords: "cross product vector" },
  { id: "vecmag", category: "linalg", name: "Vector magnitude",
    latex: "|\\vec v| = \\sqrt{v_1^2 + v_2^2 + v_3^2}",
    keywords: "vector magnitude norm length" },
  { id: "proj", category: "linalg", name: "Vector projection",
    latex: "\\text{proj}_{\\vec b}\\vec a = \\frac{\\vec a \\cdot \\vec b}{|\\vec b|^2}\\,\\vec b",
    keywords: "projection vector" },
  { id: "eigeneq", category: "linalg", name: "Eigenvalue equation",
    latex: "A\\vec v = \\lambda \\vec v",
    keywords: "eigenvalue eigenvector" },
  { id: "char_poly", category: "linalg", name: "Characteristic polynomial",
    latex: "\\det(A - \\lambda I) = 0",
    keywords: "characteristic polynomial eigenvalue" },
  { id: "trace", category: "linalg", name: "Trace",
    latex: "\\text{tr}(A) = \\sum_i A_{ii} = \\sum_i \\lambda_i",
    keywords: "trace matrix eigenvalue" },
  { id: "matnorm", category: "linalg", name: "Frobenius norm",
    latex: "\\|A\\|_F = \\sqrt{\\sum_{i,j} |A_{ij}|^2}",
    keywords: "frobenius norm matrix" },
  { id: "svd", category: "linalg", name: "Singular value decomposition",
    latex: "A = U\\Sigma V^{T}",
    keywords: "svd singular value decomposition" },
  { id: "rank_nullity", category: "linalg", name: "Rank–nullity theorem",
    latex: "\\dim(\\ker T) + \\dim(\\text{im}\\, T) = \\dim V",
    keywords: "rank nullity kernel image" },
  { id: "cramer", category: "linalg", name: "Cramer's rule",
    latex: "x_i = \\frac{\\det(A_i)}{\\det(A)}",
    keywords: "cramer rule determinant" },
  { id: "outer", category: "linalg", name: "Outer product",
    latex: "(\\vec u \\otimes \\vec v)_{ij} = u_i v_j",
    keywords: "outer product tensor" },

  // ── Geometry ─────────────────────────────────────────────────────────────
  { id: "circle_area", category: "geometry", name: "Circle area",
    latex: "A = \\pi r^2",
    keywords: "circle area" },
  { id: "circle_circ", category: "geometry", name: "Circle circumference",
    latex: "C = 2\\pi r",
    keywords: "circle circumference" },
  { id: "sphere_vol", category: "geometry", name: "Sphere volume",
    latex: "V = \\tfrac{4}{3}\\pi r^3",
    keywords: "sphere volume" },
  { id: "sphere_sa", category: "geometry", name: "Sphere surface area",
    latex: "A = 4\\pi r^2",
    keywords: "sphere surface area" },
  { id: "cyl_vol", category: "geometry", name: "Cylinder volume",
    latex: "V = \\pi r^2 h",
    keywords: "cylinder volume" },
  { id: "cyl_sa", category: "geometry", name: "Cylinder surface area",
    latex: "A = 2\\pi r^2 + 2\\pi r h",
    keywords: "cylinder surface area" },
  { id: "cone_vol", category: "geometry", name: "Cone volume",
    latex: "V = \\tfrac{1}{3}\\pi r^2 h",
    keywords: "cone volume" },
  { id: "cone_sa", category: "geometry", name: "Cone surface area",
    latex: "A = \\pi r^2 + \\pi r \\sqrt{r^2 + h^2}",
    keywords: "cone surface area" },
  { id: "pyramid_vol", category: "geometry", name: "Pyramid volume",
    latex: "V = \\tfrac{1}{3} A_{\\text{base}}\\, h",
    keywords: "pyramid volume" },
  { id: "tri_area_base", category: "geometry", name: "Triangle area (base × height)",
    latex: "A = \\tfrac{1}{2} b h",
    keywords: "triangle area base height" },
  { id: "trap_area", category: "geometry", name: "Trapezoid area",
    latex: "A = \\tfrac{1}{2}(a + b)h",
    keywords: "trapezoid trapezium area" },
  { id: "heron", category: "geometry", name: "Heron's formula",
    latex: "A = \\sqrt{s(s-a)(s-b)(s-c)}, \\quad s = \\tfrac{a+b+c}{2}",
    keywords: "heron triangle area" },
  { id: "pythag", category: "geometry", name: "Pythagorean theorem",
    latex: "a^2 + b^2 = c^2",
    keywords: "pythagorean theorem right triangle" },
  { id: "dist", category: "geometry", name: "Distance formula",
    latex: "d = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}",
    keywords: "distance formula points" },
  { id: "midpt", category: "geometry", name: "Midpoint",
    latex: "M = \\left(\\tfrac{x_1+x_2}{2},\\,\\tfrac{y_1+y_2}{2}\\right)",
    keywords: "midpoint coordinate" },
  { id: "slope", category: "geometry", name: "Slope",
    latex: "m = \\frac{y_2 - y_1}{x_2 - x_1}",
    keywords: "slope gradient line" },
  { id: "line_pt_slope", category: "geometry", name: "Point–slope line",
    latex: "y - y_1 = m(x - x_1)",
    keywords: "point slope line" },
  { id: "line_si", category: "geometry", name: "Slope–intercept line",
    latex: "y = mx + b",
    keywords: "slope intercept line" },
  { id: "circle_eq", category: "geometry", name: "Circle equation",
    latex: "(x - h)^2 + (y - k)^2 = r^2",
    keywords: "circle equation centre radius" },
  { id: "ellipse_eq", category: "geometry", name: "Ellipse equation",
    latex: "\\frac{x^2}{a^2} + \\frac{y^2}{b^2} = 1",
    keywords: "ellipse equation" },
  { id: "hyperbola_eq", category: "geometry", name: "Hyperbola equation",
    latex: "\\frac{x^2}{a^2} - \\frac{y^2}{b^2} = 1",
    keywords: "hyperbola equation" },
  { id: "parabola_eq", category: "geometry", name: "Parabola equation",
    latex: "y = ax^2 + bx + c",
    keywords: "parabola quadratic" },

  // ── Statistics ───────────────────────────────────────────────────────────
  { id: "mean", category: "stats", name: "Mean",
    latex: "\\bar{x} = \\frac{1}{n}\\sum_{i=1}^{n} x_i",
    keywords: "mean average expected" },
  { id: "variance", category: "stats", name: "Variance (sample)",
    latex: "s^2 = \\frac{1}{n-1}\\sum_{i=1}^{n} (x_i - \\bar x)^2",
    keywords: "variance sample" },
  { id: "stddev", category: "stats", name: "Standard deviation (sample)",
    latex: "s = \\sqrt{\\tfrac{1}{n-1}\\sum_{i=1}^{n} (x_i - \\bar x)^2}",
    keywords: "standard deviation" },
  { id: "covariance", category: "stats", name: "Covariance",
    latex: "\\text{Cov}(X,Y) = E[(X - \\mu_X)(Y - \\mu_Y)]",
    keywords: "covariance" },
  { id: "correlation", category: "stats", name: "Correlation coefficient",
    latex: "\\rho_{XY} = \\frac{\\text{Cov}(X,Y)}{\\sigma_X \\sigma_Y}",
    keywords: "correlation pearson" },
  { id: "zscore", category: "stats", name: "Z-score",
    latex: "z = \\frac{x - \\mu}{\\sigma}",
    keywords: "z score standard" },
  { id: "normal_pdf", category: "stats", name: "Normal PDF",
    latex: "f(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}}\\,e^{-\\,(x-\\mu)^2 / (2\\sigma^2)}",
    keywords: "normal gaussian pdf" },
  { id: "stdnormal", category: "stats", name: "Standard normal PDF",
    latex: "\\phi(z) = \\frac{1}{\\sqrt{2\\pi}}\\,e^{-z^2/2}",
    keywords: "standard normal" },
  { id: "binomial_pmf", category: "stats", name: "Binomial PMF",
    latex: "P(X=k) = \\binom{n}{k} p^k (1-p)^{n-k}",
    keywords: "binomial probability" },
  { id: "poisson_pmf", category: "stats", name: "Poisson PMF",
    latex: "P(X=k) = \\frac{\\lambda^k e^{-\\lambda}}{k!}",
    keywords: "poisson probability" },
  { id: "geom_pmf", category: "stats", name: "Geometric PMF",
    latex: "P(X=k) = (1-p)^{k-1} p",
    keywords: "geometric probability" },
  { id: "exp_pdf", category: "stats", name: "Exponential PDF",
    latex: "f(x) = \\lambda e^{-\\lambda x}, \\quad x \\ge 0",
    keywords: "exponential probability" },
  { id: "uniform_pdf", category: "stats", name: "Uniform PDF",
    latex: "f(x) = \\frac{1}{b-a}, \\quad a \\le x \\le b",
    keywords: "uniform probability" },
  { id: "bayes", category: "stats", name: "Bayes' theorem",
    latex: "P(A|B) = \\frac{P(B|A)\\,P(A)}{P(B)}",
    keywords: "bayes theorem conditional" },
  { id: "cond_prob", category: "stats", name: "Conditional probability",
    latex: "P(A|B) = \\frac{P(A \\cap B)}{P(B)}",
    keywords: "conditional probability" },
  { id: "perm", category: "stats", name: "Permutations",
    latex: "P(n,k) = \\frac{n!}{(n-k)!}",
    keywords: "permutation" },
  { id: "comb", category: "stats", name: "Combinations",
    latex: "C(n,k) = \\binom{n}{k} = \\frac{n!}{k!(n-k)!}",
    keywords: "combination choose" },
  { id: "exp_val", category: "stats", name: "Expected value",
    latex: "E[X] = \\sum_x x\\,P(X=x) = \\int x\\,f(x)\\,dx",
    keywords: "expected value expectation" },
  { id: "var_def", category: "stats", name: "Variance (definition)",
    latex: "\\text{Var}(X) = E[(X - E[X])^2] = E[X^2] - E[X]^2",
    keywords: "variance definition" },
  { id: "linreg", category: "stats", name: "Linear regression",
    latex: "\\hat y = \\beta_0 + \\beta_1 x",
    keywords: "linear regression" },
  { id: "lse_slope", category: "stats", name: "Least-squares slope",
    latex: "\\hat\\beta_1 = \\frac{\\sum_i (x_i - \\bar x)(y_i - \\bar y)}{\\sum_i (x_i - \\bar x)^2}",
    keywords: "least squares slope" },
  { id: "ci_mean", category: "stats", name: "Confidence interval (mean, σ known)",
    latex: "\\bar x \\pm z_{\\alpha/2}\\,\\frac{\\sigma}{\\sqrt{n}}",
    keywords: "confidence interval mean" },
  { id: "tstat", category: "stats", name: "t-statistic",
    latex: "t = \\frac{\\bar x - \\mu_0}{s/\\sqrt{n}}",
    keywords: "t test statistic" },
  { id: "chisq", category: "stats", name: "Chi-square statistic",
    latex: "\\chi^2 = \\sum_i \\frac{(O_i - E_i)^2}{E_i}",
    keywords: "chi square test" },
  { id: "stderr", category: "stats", name: "Standard error of mean",
    latex: "\\text{SE} = \\frac{\\sigma}{\\sqrt{n}}",
    keywords: "standard error mean" },

  // ── Discrete & Number Theory ─────────────────────────────────────────────
  { id: "fermat_little", category: "discrete", name: "Fermat's little theorem",
    latex: "a^{p-1} \\equiv 1 \\pmod{p}, \\quad \\gcd(a,p)=1",
    keywords: "fermat little theorem" },
  { id: "euler_thm", category: "discrete", name: "Euler's theorem",
    latex: "a^{\\varphi(n)} \\equiv 1 \\pmod{n}, \\quad \\gcd(a,n)=1",
    keywords: "euler theorem totient" },
  { id: "totient", category: "discrete", name: "Euler's totient",
    latex: "\\varphi(n) = n\\prod_{p \\mid n}\\left(1 - \\tfrac{1}{p}\\right)",
    keywords: "totient phi function" },
  { id: "gcd_id", category: "discrete", name: "Bezout's identity",
    latex: "\\gcd(a,b) = ax + by",
    keywords: "bezout gcd" },
  { id: "modinv", category: "discrete", name: "Modular inverse",
    latex: "a \\cdot a^{-1} \\equiv 1 \\pmod{n}",
    keywords: "modular inverse" },
  { id: "pigeonhole", category: "discrete", name: "Pigeonhole principle",
    latex: "n+1 \\text{ items, } n \\text{ boxes} \\Rightarrow \\text{some box has} \\ge 2",
    keywords: "pigeonhole principle" },
  { id: "incl_excl", category: "discrete", name: "Inclusion–exclusion",
    latex: "|A \\cup B| = |A| + |B| - |A \\cap B|",
    keywords: "inclusion exclusion" },
  { id: "stirling", category: "discrete", name: "Stirling's approximation",
    latex: "n! \\approx \\sqrt{2\\pi n}\\,\\left(\\tfrac{n}{e}\\right)^{\\!n}",
    keywords: "stirling approximation factorial" },
  { id: "fib", category: "discrete", name: "Fibonacci recurrence",
    latex: "F_n = F_{n-1} + F_{n-2}, \\; F_0 = 0, F_1 = 1",
    keywords: "fibonacci recurrence" },
  { id: "fib_closed", category: "discrete", name: "Fibonacci closed form",
    latex: "F_n = \\frac{\\varphi^n - \\psi^n}{\\sqrt{5}}, \\; \\varphi = \\tfrac{1+\\sqrt 5}{2}",
    keywords: "fibonacci binet golden" },
  { id: "harmonic", category: "discrete", name: "Harmonic series partial sum",
    latex: "H_n = \\sum_{k=1}^{n} \\frac{1}{k} \\approx \\ln n + \\gamma",
    keywords: "harmonic series" },
  { id: "master_thm", category: "discrete", name: "Master theorem (recurrence)",
    latex: "T(n) = aT(n/b) + f(n)",
    keywords: "master theorem recurrence algorithm" },
  { id: "modadd", category: "discrete", name: "Modular addition",
    latex: "(a + b) \\bmod n = ((a \\bmod n) + (b \\bmod n)) \\bmod n",
    keywords: "modular addition" },
  { id: "modmul", category: "discrete", name: "Modular multiplication",
    latex: "(ab) \\bmod n = ((a \\bmod n)(b \\bmod n)) \\bmod n",
    keywords: "modular multiplication" },
  { id: "primecount", category: "discrete", name: "Prime counting (PNT)",
    latex: "\\pi(n) \\sim \\frac{n}{\\ln n}",
    keywords: "prime number theorem" },

  // ── Mechanics ────────────────────────────────────────────────────────────
  { id: "newton2", category: "mechanics", name: "Newton's second law",
    latex: "\\vec F = m\\vec a",
    keywords: "newton second law force mass" },
  { id: "kin_v", category: "mechanics", name: "Kinematics (v from u, a, t)",
    latex: "v = u + at",
    keywords: "kinematics velocity acceleration" },
  { id: "kin_s", category: "mechanics", name: "Kinematics (s from u, t, a)",
    latex: "s = ut + \\tfrac{1}{2}at^2",
    keywords: "kinematics displacement" },
  { id: "kin_v2", category: "mechanics", name: "Kinematics (v² = u² + 2as)",
    latex: "v^2 = u^2 + 2as",
    keywords: "kinematics velocity displacement" },
  { id: "kin_s_avg", category: "mechanics", name: "Kinematics (average velocity)",
    latex: "s = \\tfrac{1}{2}(u + v)\\,t",
    keywords: "kinematics average velocity" },
  { id: "momentum", category: "mechanics", name: "Linear momentum",
    latex: "\\vec p = m\\vec v",
    keywords: "momentum linear" },
  { id: "impulse", category: "mechanics", name: "Impulse",
    latex: "\\vec J = \\Delta \\vec p = \\int \\vec F\\,dt",
    keywords: "impulse momentum change" },
  { id: "ke", category: "mechanics", name: "Kinetic energy",
    latex: "KE = \\tfrac{1}{2} m v^2",
    keywords: "kinetic energy" },
  { id: "pe_grav", category: "mechanics", name: "Gravitational PE",
    latex: "PE = mgh",
    keywords: "potential energy gravitational" },
  { id: "pe_spring", category: "mechanics", name: "Spring PE",
    latex: "PE_s = \\tfrac{1}{2} k x^2",
    keywords: "spring potential energy hooke" },
  { id: "work", category: "mechanics", name: "Work",
    latex: "W = \\int \\vec F \\cdot d\\vec r",
    keywords: "work done force" },
  { id: "power", category: "mechanics", name: "Power",
    latex: "P = \\frac{dW}{dt} = \\vec F \\cdot \\vec v",
    keywords: "power work rate" },
  { id: "hooke", category: "mechanics", name: "Hooke's law",
    latex: "F = -kx",
    keywords: "hooke spring force" },
  { id: "centripetal_acc", category: "mechanics", name: "Centripetal acceleration",
    latex: "a_c = \\frac{v^2}{r} = \\omega^2 r",
    keywords: "centripetal acceleration circular" },
  { id: "centripetal_f", category: "mechanics", name: "Centripetal force",
    latex: "F_c = \\frac{m v^2}{r}",
    keywords: "centripetal force circular" },
  { id: "torque", category: "mechanics", name: "Torque",
    latex: "\\vec\\tau = \\vec r \\times \\vec F",
    keywords: "torque moment force" },
  { id: "ang_mom", category: "mechanics", name: "Angular momentum",
    latex: "\\vec L = \\vec r \\times \\vec p = I\\vec\\omega",
    keywords: "angular momentum" },
  { id: "rot_ke", category: "mechanics", name: "Rotational KE",
    latex: "KE_{\\text{rot}} = \\tfrac{1}{2} I \\omega^2",
    keywords: "rotational kinetic energy" },
  { id: "I_disk", category: "mechanics", name: "Moment of inertia (disk)",
    latex: "I = \\tfrac{1}{2} m r^2",
    keywords: "moment inertia disk" },
  { id: "I_sphere", category: "mechanics", name: "Moment of inertia (solid sphere)",
    latex: "I = \\tfrac{2}{5} m r^2",
    keywords: "moment inertia sphere" },
  { id: "I_rod_mid", category: "mechanics", name: "Moment of inertia (rod, centre)",
    latex: "I = \\tfrac{1}{12} m L^2",
    keywords: "moment inertia rod centre" },
  { id: "pendulum_T", category: "mechanics", name: "Pendulum period",
    latex: "T = 2\\pi \\sqrt{\\tfrac{L}{g}}",
    keywords: "pendulum period oscillation" },
  { id: "spring_T", category: "mechanics", name: "Spring period",
    latex: "T = 2\\pi \\sqrt{\\tfrac{m}{k}}",
    keywords: "spring period oscillation" },
  { id: "univ_grav", category: "mechanics", name: "Universal gravitation",
    latex: "F = G\\,\\frac{m_1 m_2}{r^2}",
    keywords: "newton gravitation" },
  { id: "esc_v", category: "mechanics", name: "Escape velocity",
    latex: "v_{\\text{esc}} = \\sqrt{\\tfrac{2GM}{r}}",
    keywords: "escape velocity" },
  { id: "orb_v", category: "mechanics", name: "Orbital velocity",
    latex: "v_{\\text{orb}} = \\sqrt{\\tfrac{GM}{r}}",
    keywords: "orbital velocity" },
  { id: "kepler3", category: "mechanics", name: "Kepler's third law",
    latex: "T^2 = \\frac{4\\pi^2}{GM}\\,a^3",
    keywords: "kepler third law orbit" },

  // ── Electromagnetism ─────────────────────────────────────────────────────
  { id: "coulomb", category: "em", name: "Coulomb's law",
    latex: "F = \\frac{1}{4\\pi\\varepsilon_0}\\,\\frac{q_1 q_2}{r^2}",
    keywords: "coulomb law electric force" },
  { id: "efield_pt", category: "em", name: "Electric field of point charge",
    latex: "E = \\frac{1}{4\\pi\\varepsilon_0}\\,\\frac{q}{r^2}",
    keywords: "electric field point charge" },
  { id: "gauss_e_int", category: "em", name: "Gauss's law (integral)",
    latex: "\\oiint_{\\partial V} \\vec E \\cdot d\\vec A = \\frac{Q_{\\text{enc}}}{\\varepsilon_0}",
    keywords: "gauss law electric integral" },
  { id: "gauss_e_diff", category: "em", name: "Gauss's law (differential)",
    latex: "\\nabla \\cdot \\vec E = \\frac{\\rho}{\\varepsilon_0}",
    keywords: "gauss law electric differential" },
  { id: "gauss_b_diff", category: "em", name: "Gauss's law for magnetism",
    latex: "\\nabla \\cdot \\vec B = 0",
    keywords: "gauss law magnetic monopole" },
  { id: "faraday_diff", category: "em", name: "Faraday's law (differential)",
    latex: "\\nabla \\times \\vec E = -\\frac{\\partial \\vec B}{\\partial t}",
    keywords: "faraday law induction differential" },
  { id: "ampere_max_diff", category: "em", name: "Ampère–Maxwell law",
    latex: "\\nabla \\times \\vec B = \\mu_0 \\vec J + \\mu_0 \\varepsilon_0 \\frac{\\partial \\vec E}{\\partial t}",
    keywords: "ampere maxwell law" },
  { id: "lorentz_force", category: "em", name: "Lorentz force",
    latex: "\\vec F = q(\\vec E + \\vec v \\times \\vec B)",
    keywords: "lorentz force charge magnetic" },
  { id: "ohm", category: "em", name: "Ohm's law",
    latex: "V = IR",
    keywords: "ohm law voltage current resistance" },
  { id: "power_elec", category: "em", name: "Electrical power",
    latex: "P = VI = I^2 R = \\frac{V^2}{R}",
    keywords: "electrical power" },
  { id: "capacitance", category: "em", name: "Capacitance",
    latex: "C = \\frac{Q}{V}",
    keywords: "capacitance charge voltage" },
  { id: "cap_parallel_plate", category: "em", name: "Parallel-plate capacitance",
    latex: "C = \\frac{\\varepsilon_0 A}{d}",
    keywords: "parallel plate capacitor" },
  { id: "cap_energy", category: "em", name: "Energy in capacitor",
    latex: "U = \\tfrac{1}{2} C V^2 = \\tfrac{Q^2}{2C}",
    keywords: "capacitor energy" },
  { id: "ind_energy", category: "em", name: "Energy in inductor",
    latex: "U = \\tfrac{1}{2} L I^2",
    keywords: "inductor energy" },
  { id: "rc_tau", category: "em", name: "RC time constant",
    latex: "\\tau = RC",
    keywords: "rc time constant" },
  { id: "rl_tau", category: "em", name: "RL time constant",
    latex: "\\tau = \\frac{L}{R}",
    keywords: "rl time constant" },
  { id: "lc_freq", category: "em", name: "LC resonance frequency",
    latex: "\\omega_0 = \\frac{1}{\\sqrt{LC}}",
    keywords: "lc resonance frequency" },
  { id: "biot_savart", category: "em", name: "Biot–Savart law",
    latex: "d\\vec B = \\frac{\\mu_0}{4\\pi}\\,\\frac{I\\,d\\vec\\ell \\times \\hat r}{r^2}",
    keywords: "biot savart magnetic field" },
  { id: "poynting", category: "em", name: "Poynting vector",
    latex: "\\vec S = \\frac{1}{\\mu_0}\\,\\vec E \\times \\vec B",
    keywords: "poynting vector energy flux" },
  { id: "em_wave_speed", category: "em", name: "EM wave speed",
    latex: "c = \\frac{1}{\\sqrt{\\mu_0 \\varepsilon_0}}",
    keywords: "electromagnetic wave speed light" },

  // ── Thermodynamics ───────────────────────────────────────────────────────
  { id: "ideal_gas", category: "thermo", name: "Ideal gas law",
    latex: "PV = nRT",
    keywords: "ideal gas pv nrt" },
  { id: "first_law", category: "thermo", name: "First law of thermodynamics",
    latex: "\\Delta U = Q - W",
    keywords: "first law thermodynamics energy" },
  { id: "second_law", category: "thermo", name: "Second law (entropy)",
    latex: "\\Delta S_{\\text{universe}} \\ge 0",
    keywords: "second law entropy" },
  { id: "entropy_change", category: "thermo", name: "Entropy change",
    latex: "\\Delta S = \\int \\frac{dQ_{\\text{rev}}}{T}",
    keywords: "entropy change reversible" },
  { id: "carnot_eta", category: "thermo", name: "Carnot efficiency",
    latex: "\\eta = 1 - \\frac{T_C}{T_H}",
    keywords: "carnot efficiency heat engine" },
  { id: "heat_q", category: "thermo", name: "Heat (specific heat)",
    latex: "Q = mc\\Delta T",
    keywords: "heat specific" },
  { id: "stefan_boltz", category: "thermo", name: "Stefan–Boltzmann",
    latex: "j = \\sigma T^4",
    keywords: "stefan boltzmann radiation" },
  { id: "wien", category: "thermo", name: "Wien's displacement law",
    latex: "\\lambda_{\\max} T = b",
    keywords: "wien displacement law" },
  { id: "boltz_dist", category: "thermo", name: "Boltzmann distribution",
    latex: "P(E) \\propto e^{-E/(k_B T)}",
    keywords: "boltzmann distribution" },
  { id: "max_boltz_v", category: "thermo", name: "Maxwell–Boltzmann speed",
    latex: "f(v) = 4\\pi n\\!\\left(\\tfrac{m}{2\\pi k_B T}\\right)^{\\!3/2}\\!v^2 e^{-mv^2/(2k_B T)}",
    keywords: "maxwell boltzmann speed distribution" },
  { id: "U_ideal", category: "thermo", name: "Internal energy of ideal gas",
    latex: "U = \\tfrac{f}{2} n R T",
    keywords: "internal energy ideal gas" },
  { id: "enthalpy", category: "thermo", name: "Enthalpy",
    latex: "H = U + PV",
    keywords: "enthalpy" },
  { id: "gibbs", category: "thermo", name: "Gibbs free energy",
    latex: "G = H - TS",
    keywords: "gibbs free energy" },
  { id: "delta_g_rxn", category: "thermo", name: "Δ G of reaction",
    latex: "\\Delta G = \\Delta H - T\\Delta S",
    keywords: "delta g reaction" },
  { id: "fourier_heat", category: "thermo", name: "Fourier heat conduction",
    latex: "q = -k\\nabla T",
    keywords: "fourier heat conduction" },

  // ── Quantum ──────────────────────────────────────────────────────────────
  { id: "schrod_td", category: "quantum", name: "Time-dependent Schrödinger",
    latex: "i\\hbar\\,\\frac{\\partial \\psi}{\\partial t} = \\hat H \\psi",
    keywords: "schrodinger time dependent" },
  { id: "schrod_ti", category: "quantum", name: "Time-independent Schrödinger",
    latex: "\\hat H \\psi = E \\psi",
    keywords: "schrodinger time independent" },
  { id: "ham_kin", category: "quantum", name: "Hamiltonian (1D)",
    latex: "\\hat H = -\\frac{\\hbar^2}{2m}\\nabla^2 + V(\\vec r)",
    keywords: "hamiltonian kinetic potential" },
  { id: "p_op", category: "quantum", name: "Momentum operator",
    latex: "\\hat p = -i\\hbar\\,\\nabla",
    keywords: "momentum operator" },
  { id: "x_op", category: "quantum", name: "Position operator",
    latex: "\\hat x \\psi(x) = x\\psi(x)",
    keywords: "position operator" },
  { id: "commutator", category: "quantum", name: "Canonical commutator",
    latex: "[\\hat x, \\hat p] = i\\hbar",
    keywords: "commutator position momentum" },
  { id: "uncertainty", category: "quantum", name: "Heisenberg uncertainty",
    latex: "\\Delta x\\,\\Delta p \\ge \\frac{\\hbar}{2}",
    keywords: "heisenberg uncertainty" },
  { id: "planck_einstein", category: "quantum", name: "Planck–Einstein relation",
    latex: "E = h\\nu = \\hbar\\omega",
    keywords: "planck einstein photon energy" },
  { id: "de_broglie", category: "quantum", name: "de Broglie wavelength",
    latex: "\\lambda = \\frac{h}{p}",
    keywords: "de broglie wavelength" },
  { id: "hydrogen_E", category: "quantum", name: "Hydrogen energy levels",
    latex: "E_n = -\\frac{13.6\\,\\text{eV}}{n^2}",
    keywords: "hydrogen energy levels rydberg" },
  { id: "pib_E", category: "quantum", name: "Particle-in-a-box energies",
    latex: "E_n = \\frac{n^2 \\pi^2 \\hbar^2}{2 m L^2}",
    keywords: "particle box energy" },
  { id: "ho_E", category: "quantum", name: "Harmonic oscillator energies",
    latex: "E_n = \\hbar\\omega\\!\\left(n + \\tfrac{1}{2}\\right)",
    keywords: "harmonic oscillator energy quantum" },
  { id: "psi_prob", category: "quantum", name: "Wave-function probability",
    latex: "P(a \\le x \\le b) = \\int_a^b |\\psi(x)|^2\\,dx",
    keywords: "wave function probability" },
  { id: "expect", category: "quantum", name: "Expectation value",
    latex: "\\langle \\hat A\\rangle = \\int \\psi^* \\hat A \\psi\\,dx",
    keywords: "expectation value operator" },
  { id: "spin_pauli_z", category: "quantum", name: "Pauli σz",
    latex: "\\sigma_z = \\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}",
    keywords: "pauli matrix sigma z" },

  // ── Relativity ───────────────────────────────────────────────────────────
  { id: "lorentz_t", category: "relativity", name: "Lorentz transformation (time)",
    latex: "t' = \\gamma\\!\\left(t - \\tfrac{vx}{c^2}\\right)",
    keywords: "lorentz transformation time" },
  { id: "lorentz_x", category: "relativity", name: "Lorentz transformation (position)",
    latex: "x' = \\gamma(x - vt)",
    keywords: "lorentz transformation position" },
  { id: "gamma_factor", category: "relativity", name: "Lorentz factor γ",
    latex: "\\gamma = \\frac{1}{\\sqrt{1 - v^2/c^2}}",
    keywords: "gamma lorentz factor" },
  { id: "time_dilate", category: "relativity", name: "Time dilation",
    latex: "\\Delta t = \\gamma\\,\\Delta t_0",
    keywords: "time dilation relativity" },
  { id: "len_contract", category: "relativity", name: "Length contraction",
    latex: "L = \\frac{L_0}{\\gamma}",
    keywords: "length contraction relativity" },
  { id: "rel_p", category: "relativity", name: "Relativistic momentum",
    latex: "\\vec p = \\gamma m \\vec v",
    keywords: "relativistic momentum" },
  { id: "rel_E", category: "relativity", name: "Relativistic energy",
    latex: "E = \\gamma m c^2",
    keywords: "relativistic energy" },
  { id: "mc2", category: "relativity", name: "Mass-energy equivalence",
    latex: "E = mc^2",
    keywords: "einstein mass energy equivalence" },
  { id: "energy_momentum", category: "relativity", name: "Energy–momentum relation",
    latex: "E^2 = (pc)^2 + (mc^2)^2",
    keywords: "energy momentum relation relativistic" },
  { id: "vel_add", category: "relativity", name: "Relativistic velocity addition",
    latex: "u' = \\frac{u - v}{1 - uv/c^2}",
    keywords: "velocity addition relativistic" },
  { id: "schwarz_r", category: "relativity", name: "Schwarzschild radius",
    latex: "r_s = \\frac{2GM}{c^2}",
    keywords: "schwarzschild radius black hole" },

  // ── Optics & Waves ───────────────────────────────────────────────────────
  { id: "wave_speed", category: "optics", name: "Wave speed",
    latex: "v = f\\lambda",
    keywords: "wave speed frequency wavelength" },
  { id: "wave_eq", category: "optics", name: "Wave equation",
    latex: "\\frac{\\partial^2 u}{\\partial t^2} = v^2 \\nabla^2 u",
    keywords: "wave equation" },
  { id: "snell", category: "optics", name: "Snell's law",
    latex: "n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2",
    keywords: "snell law refraction" },
  { id: "lens_eq", category: "optics", name: "Thin lens equation",
    latex: "\\frac{1}{f} = \\frac{1}{d_o} + \\frac{1}{d_i}",
    keywords: "lens equation thin" },
  { id: "magnification", category: "optics", name: "Magnification",
    latex: "M = -\\frac{d_i}{d_o} = \\frac{h_i}{h_o}",
    keywords: "magnification optics" },
  { id: "young_double", category: "optics", name: "Young's double slit",
    latex: "d\\sin\\theta = m\\lambda",
    keywords: "young double slit interference" },
  { id: "diffraction", category: "optics", name: "Single-slit diffraction",
    latex: "a\\sin\\theta = m\\lambda",
    keywords: "diffraction single slit" },
  { id: "bragg", category: "optics", name: "Bragg's law",
    latex: "n\\lambda = 2d\\sin\\theta",
    keywords: "bragg law diffraction" },
  { id: "doppler", category: "optics", name: "Doppler effect (sound)",
    latex: "f' = f\\,\\frac{v + v_o}{v - v_s}",
    keywords: "doppler effect frequency" },
  { id: "intensity_inv_sq", category: "optics", name: "Inverse-square intensity",
    latex: "I = \\frac{P}{4\\pi r^2}",
    keywords: "intensity inverse square" },

  // ── Chemistry ────────────────────────────────────────────────────────────
  { id: "ph", category: "chemistry", name: "pH",
    latex: "\\text{pH} = -\\log_{10}[H^+]",
    keywords: "ph hydrogen ion" },
  { id: "poh", category: "chemistry", name: "pOH",
    latex: "\\text{pOH} = -\\log_{10}[OH^-]",
    keywords: "poh hydroxide" },
  { id: "ph_poh", category: "chemistry", name: "pH + pOH",
    latex: "\\text{pH} + \\text{pOH} = 14",
    keywords: "ph poh sum" },
  { id: "henderson", category: "chemistry", name: "Henderson–Hasselbalch",
    latex: "\\text{pH} = pK_a + \\log\\!\\left(\\tfrac{[A^-]}{[HA]}\\right)",
    keywords: "henderson hasselbalch buffer" },
  { id: "kc", category: "chemistry", name: "Equilibrium constant",
    latex: "K_c = \\frac{[C]^c [D]^d}{[A]^a [B]^b}",
    keywords: "equilibrium constant kc" },
  { id: "rate_law", category: "chemistry", name: "Rate law",
    latex: "r = k[A]^m [B]^n",
    keywords: "rate law kinetics" },
  { id: "arrhenius", category: "chemistry", name: "Arrhenius equation",
    latex: "k = A\\,e^{-E_a/(RT)}",
    keywords: "arrhenius equation activation energy" },
  { id: "beer_lambert", category: "chemistry", name: "Beer–Lambert law",
    latex: "A = \\varepsilon\\,c\\,\\ell",
    keywords: "beer lambert absorbance" },
  { id: "comb_methane", category: "chemistry", name: "Methane combustion",
    latex: "\\ce{CH4 + 2O2 -> CO2 + 2H2O}",
    keywords: "combustion methane" },
  { id: "photosyn", category: "chemistry", name: "Photosynthesis",
    latex: "\\ce{6CO2 + 6H2O -> C6H12O6 + 6O2}",
    keywords: "photosynthesis" },
  { id: "respiration", category: "chemistry", name: "Cellular respiration",
    latex: "\\ce{C6H12O6 + 6O2 -> 6CO2 + 6H2O}",
    keywords: "respiration cellular glucose" },
  { id: "haber", category: "chemistry", name: "Haber process",
    latex: "\\ce{N2 + 3H2 <=> 2NH3}",
    keywords: "haber ammonia nitrogen" },
  { id: "neutralisation", category: "chemistry", name: "Acid–base neutralisation",
    latex: "\\ce{HCl + NaOH -> NaCl + H2O}",
    keywords: "neutralisation acid base" },
  { id: "water_diss", category: "chemistry", name: "Water dissociation",
    latex: "\\ce{H2O <=> H+ + OH-}",
    keywords: "water dissociation autoionization" },
  { id: "kw", category: "chemistry", name: "Water ionization product",
    latex: "K_w = [H^+][OH^-] = 10^{-14}",
    keywords: "water ionization kw" },
  { id: "molarity", category: "chemistry", name: "Molarity",
    latex: "M = \\frac{n_{\\text{solute}}}{V_{\\text{solution}}}",
    keywords: "molarity concentration" },
  { id: "molality", category: "chemistry", name: "Molality",
    latex: "m = \\frac{n_{\\text{solute}}}{\\text{kg solvent}}",
    keywords: "molality concentration" },
  { id: "gibbs_eq", category: "chemistry", name: "Gibbs free energy of reaction",
    latex: "\\Delta G = -RT \\ln K",
    keywords: "gibbs free energy reaction equilibrium" },
  { id: "nernst", category: "chemistry", name: "Nernst equation",
    latex: "E = E^\\circ - \\frac{RT}{nF}\\ln Q",
    keywords: "nernst electrochemistry" },
  { id: "raoult", category: "chemistry", name: "Raoult's law",
    latex: "P_i = x_i\\,P_i^*",
    keywords: "raoult law partial pressure" },
  { id: "freezing_pt", category: "chemistry", name: "Freezing-point depression",
    latex: "\\Delta T_f = K_f\\,m\\,i",
    keywords: "freezing point depression" },
  { id: "boiling_pt", category: "chemistry", name: "Boiling-point elevation",
    latex: "\\Delta T_b = K_b\\,m\\,i",
    keywords: "boiling point elevation" },
  { id: "michaelis", category: "chemistry", name: "Michaelis–Menten",
    latex: "v = \\frac{V_{\\max}[S]}{K_M + [S]}",
    keywords: "michaelis menten enzyme kinetics" },

  // ── Chemistry — Gas laws ─────────────────────────────────────────────────
  { id: "boyle", category: "chemistry", name: "Boyle's law",
    latex: "P_1 V_1 = P_2 V_2",
    notes: "Constant temperature, fixed amount of gas",
    keywords: "boyle law gas pressure volume" },
  { id: "charles", category: "chemistry", name: "Charles's law",
    latex: "\\frac{V_1}{T_1} = \\frac{V_2}{T_2}",
    notes: "Constant pressure",
    keywords: "charles law gas volume temperature" },
  { id: "gay_lussac", category: "chemistry", name: "Gay-Lussac's law",
    latex: "\\frac{P_1}{T_1} = \\frac{P_2}{T_2}",
    notes: "Constant volume",
    keywords: "gay-lussac law gas pressure temperature" },
  { id: "combined_gas", category: "chemistry", name: "Combined gas law",
    latex: "\\frac{P_1 V_1}{T_1} = \\frac{P_2 V_2}{T_2}",
    keywords: "combined gas law" },
  { id: "dalton_partial", category: "chemistry", name: "Dalton's partial pressures",
    latex: "P_{\\text{total}} = \\sum_i P_i",
    keywords: "dalton partial pressure gas mixture" },
  { id: "graham", category: "chemistry", name: "Graham's law of effusion",
    latex: "\\frac{r_1}{r_2} = \\sqrt{\\frac{M_2}{M_1}}",
    keywords: "graham effusion diffusion gas" },
  { id: "vdw", category: "chemistry", name: "Van der Waals equation",
    latex: "\\left(P + \\frac{an^2}{V^2}\\right)(V - nb) = nRT",
    notes: "Real gas correction",
    keywords: "van der waals real gas" },

  // ── Chemistry — Acid-base & equilibrium ──────────────────────────────────
  { id: "ka", category: "chemistry", name: "Acid dissociation constant Ka",
    latex: "K_a = \\frac{[H^+][A^-]}{[HA]}",
    keywords: "acid dissociation constant ka" },
  { id: "kb", category: "chemistry", name: "Base dissociation constant Kb",
    latex: "K_b = \\frac{[BH^+][OH^-]}{[B]}",
    keywords: "base dissociation constant kb" },
  { id: "ka_kb_kw", category: "chemistry", name: "Ka · Kb = Kw",
    latex: "K_a \\cdot K_b = K_w",
    notes: "For a conjugate acid-base pair",
    keywords: "ka kb kw conjugate" },
  { id: "pka", category: "chemistry", name: "pKa definition",
    latex: "pK_a = -\\log_{10} K_a",
    keywords: "pka acid strength" },
  { id: "reaction_quotient", category: "chemistry", name: "Reaction quotient Q",
    latex: "Q = \\frac{[C]^c [D]^d}{[A]^a [B]^b}",
    notes: "Same form as Kc but with non-equilibrium concentrations",
    keywords: "reaction quotient q equilibrium" },
  { id: "gibbs_non_std", category: "chemistry", name: "ΔG (non-standard)",
    latex: "\\Delta G = \\Delta G^{\\circ} + RT \\ln Q",
    keywords: "gibbs free energy non standard reaction quotient" },
  { id: "vant_hoff_eq", category: "chemistry", name: "Van't Hoff equation",
    latex: "\\ln\\!\\left(\\tfrac{K_2}{K_1}\\right) = -\\tfrac{\\Delta H^{\\circ}}{R}\\!\\left(\\tfrac{1}{T_2} - \\tfrac{1}{T_1}\\right)",
    keywords: "van't hoff equilibrium temperature" },

  // ── Chemistry — Kinetics ─────────────────────────────────────────────────
  { id: "rate_1st_int", category: "chemistry", name: "1st-order integrated rate law",
    latex: "\\ln[A]_t = \\ln[A]_0 - kt",
    keywords: "first order rate kinetics integrated" },
  { id: "rate_2nd_int", category: "chemistry", name: "2nd-order integrated rate law",
    latex: "\\frac{1}{[A]_t} = \\frac{1}{[A]_0} + kt",
    keywords: "second order rate kinetics integrated" },
  { id: "rate_0_int", category: "chemistry", name: "0-order integrated rate law",
    latex: "[A]_t = [A]_0 - kt",
    keywords: "zero order rate kinetics integrated" },
  { id: "half_life_1st", category: "chemistry", name: "First-order half-life",
    latex: "t_{1/2} = \\frac{\\ln 2}{k}",
    notes: "Independent of starting concentration",
    keywords: "half life first order" },
  { id: "half_life_2nd", category: "chemistry", name: "Second-order half-life",
    latex: "t_{1/2} = \\frac{1}{k[A]_0}",
    keywords: "half life second order" },

  // ── Chemistry — Thermochemistry ──────────────────────────────────────────
  { id: "hess", category: "chemistry", name: "Hess's law",
    latex: "\\Delta H_{\\text{rxn}}^{\\circ} = \\sum n\\,\\Delta H_f^{\\circ}(\\text{products}) - \\sum n\\,\\Delta H_f^{\\circ}(\\text{reactants})",
    keywords: "hess law enthalpy formation" },
  { id: "bond_enthalpy", category: "chemistry", name: "Bond enthalpy estimate",
    latex: "\\Delta H \\approx \\sum E_{\\text{broken}} - \\sum E_{\\text{formed}}",
    keywords: "bond enthalpy energy" },
  { id: "latent_heat", category: "chemistry", name: "Latent heat",
    latex: "q = mL",
    notes: "Phase-change energy; L is specific latent heat",
    keywords: "latent heat phase change" },
  { id: "entropy_universe", category: "chemistry", name: "ΔS of universe",
    latex: "\\Delta S_{\\text{univ}} = \\Delta S_{\\text{sys}} + \\Delta S_{\\text{surr}}",
    keywords: "entropy universe second law" },

  // ── Chemistry — Electrochemistry ─────────────────────────────────────────
  { id: "e_cell", category: "chemistry", name: "Standard cell potential",
    latex: "E^{\\circ}_{\\text{cell}} = E^{\\circ}_{\\text{cathode}} - E^{\\circ}_{\\text{anode}}",
    keywords: "cell potential electrochemistry" },
  { id: "faraday_electrolysis", category: "chemistry", name: "Faraday's law of electrolysis",
    latex: "m = \\frac{MIt}{nF}",
    notes: "Mass deposited at an electrode",
    keywords: "faraday electrolysis mass" },
  { id: "delta_g_nf", category: "chemistry", name: "ΔG and cell potential",
    latex: "\\Delta G = -nFE",
    keywords: "gibbs cell potential electrochemistry" },

  // ── Chemistry — Solutions ────────────────────────────────────────────────
  { id: "mole_fraction", category: "chemistry", name: "Mole fraction",
    latex: "x_i = \\frac{n_i}{n_{\\text{total}}}",
    keywords: "mole fraction concentration" },
  { id: "mass_percent", category: "chemistry", name: "Mass percent",
    latex: "\\%\\,\\text{mass} = \\frac{m_{\\text{solute}}}{m_{\\text{solution}}} \\times 100",
    keywords: "mass percent concentration" },
  { id: "osmotic_pressure", category: "chemistry", name: "Osmotic pressure",
    latex: "\\pi = MRT",
    keywords: "osmotic pressure solution" },
  { id: "dilution", category: "chemistry", name: "Dilution equation",
    latex: "M_1 V_1 = M_2 V_2",
    keywords: "dilution molarity stock" },

  // ── Chemistry — Atomic / spectroscopy ────────────────────────────────────
  { id: "rydberg_formula", category: "chemistry", name: "Rydberg formula",
    latex: "\\frac{1}{\\lambda} = R\\!\\left(\\frac{1}{n_1^2} - \\frac{1}{n_2^2}\\right)",
    notes: "Hydrogen spectral lines",
    keywords: "rydberg spectral lines hydrogen" },
  { id: "bohr_radius", category: "chemistry", name: "Bohr radius",
    latex: "a_0 = 5.292 \\times 10^{-11}\\,\\text{m}",
    keywords: "bohr radius hydrogen" },

  // ── Chemistry — Common reactions ─────────────────────────────────────────
  { id: "ethanol_combustion", category: "chemistry", name: "Ethanol combustion",
    latex: "\\ce{C2H5OH + 3O2 -> 2CO2 + 3H2O}",
    keywords: "ethanol combustion alcohol" },
  { id: "esterification", category: "chemistry", name: "Esterification (general)",
    latex: "\\ce{RCOOH + R'OH <=> RCOOR' + H2O}",
    notes: "Acid + alcohol ⇌ ester + water (Fischer)",
    keywords: "esterification ester fischer organic" },
  { id: "iron_rust", category: "chemistry", name: "Iron rusting",
    latex: "\\ce{4Fe + 3O2 -> 2Fe2O3}",
    keywords: "iron rust oxidation corrosion" },
  { id: "acid_carbonate", category: "chemistry", name: "Acid + carbonate",
    latex: "\\ce{2HCl + CaCO3 -> CaCl2 + H2O + CO2(g)}",
    notes: "Effervescence — carbon dioxide evolved",
    keywords: "acid carbonate calcium chloride hydrochloric" },

  // ── Engineering ──────────────────────────────────────────────────────────
  { id: "stress", category: "engineering", name: "Stress",
    latex: "\\sigma = \\frac{F}{A}",
    keywords: "stress force area" },
  { id: "strain", category: "engineering", name: "Strain",
    latex: "\\varepsilon = \\frac{\\Delta L}{L_0}",
    keywords: "strain length" },
  { id: "youngs", category: "engineering", name: "Young's modulus",
    latex: "E = \\frac{\\sigma}{\\varepsilon}",
    keywords: "young modulus elastic" },
  { id: "shear_mod", category: "engineering", name: "Shear modulus",
    latex: "G = \\frac{\\tau}{\\gamma}",
    keywords: "shear modulus" },
  { id: "bulk_mod", category: "engineering", name: "Bulk modulus",
    latex: "K = -V\\,\\frac{dP}{dV}",
    keywords: "bulk modulus compressibility" },
  { id: "poisson", category: "engineering", name: "Poisson's ratio",
    latex: "\\nu = -\\frac{\\varepsilon_{\\text{trans}}}{\\varepsilon_{\\text{axial}}}",
    keywords: "poisson ratio" },
  { id: "bernoulli_eq", category: "engineering", name: "Bernoulli's equation",
    latex: "P + \\tfrac{1}{2}\\rho v^2 + \\rho g h = \\text{const}",
    keywords: "bernoulli fluid pressure" },
  { id: "continuity", category: "engineering", name: "Continuity equation",
    latex: "\\rho_1 A_1 v_1 = \\rho_2 A_2 v_2",
    keywords: "continuity fluid flow" },
  { id: "reynolds", category: "engineering", name: "Reynolds number",
    latex: "\\text{Re} = \\frac{\\rho v L}{\\mu}",
    keywords: "reynolds number fluid" },
  { id: "drag", category: "engineering", name: "Drag force",
    latex: "F_D = \\tfrac{1}{2}\\rho v^2 C_D A",
    keywords: "drag force fluid" },
  { id: "decibel", category: "engineering", name: "Decibel",
    latex: "L = 10\\log_{10}\\!\\left(\\tfrac{I}{I_0}\\right)",
    keywords: "decibel sound intensity" },
  { id: "fourier_t", category: "engineering", name: "Fourier transform",
    latex: "\\hat f(\\xi) = \\int_{-\\infty}^{\\infty} f(x)\\,e^{-2\\pi i x\\xi}\\,dx",
    keywords: "fourier transform" },
  { id: "laplace_t", category: "engineering", name: "Laplace transform",
    latex: "F(s) = \\int_0^{\\infty} f(t)\\,e^{-st}\\,dt",
    keywords: "laplace transform" },
  { id: "convolution", category: "engineering", name: "Convolution",
    latex: "(f * g)(t) = \\int_{-\\infty}^{\\infty} f(\\tau)\\,g(t - \\tau)\\,d\\tau",
    keywords: "convolution signal" },
  { id: "rc_charge", category: "engineering", name: "RC charging",
    latex: "V(t) = V_0\\!\\left(1 - e^{-t/RC}\\right)",
    keywords: "rc charging exponential" },

  // ── Constants ─────────────────────────────────────────────────────────────
  { id: "c_light", category: "constants", name: "Speed of light c",
    latex: "c = 2.998 \\times 10^{8}\\,\\text{m/s}",
    keywords: "speed light constant c" },
  { id: "h_planck", category: "constants", name: "Planck's constant h",
    latex: "h = 6.626 \\times 10^{-34}\\,\\text{J}\\!\\cdot\\!\\text{s}",
    keywords: "planck constant" },
  { id: "hbar", category: "constants", name: "Reduced Planck ℏ",
    latex: "\\hbar = \\frac{h}{2\\pi} = 1.055 \\times 10^{-34}\\,\\text{J}\\!\\cdot\\!\\text{s}",
    keywords: "hbar reduced planck" },
  { id: "k_b", category: "constants", name: "Boltzmann constant k_B",
    latex: "k_B = 1.381 \\times 10^{-23}\\,\\text{J/K}",
    keywords: "boltzmann constant" },
  { id: "n_a", category: "constants", name: "Avogadro's number N_A",
    latex: "N_A = 6.022 \\times 10^{23}\\,\\text{mol}^{-1}",
    keywords: "avogadro number" },
  { id: "R_gas", category: "constants", name: "Gas constant R",
    latex: "R = 8.314\\,\\text{J/(mol}\\!\\cdot\\!\\text{K)}",
    keywords: "gas constant ideal" },
  { id: "G_grav", category: "constants", name: "Gravitational constant G",
    latex: "G = 6.674 \\times 10^{-11}\\,\\text{N}\\!\\cdot\\!\\text{m}^2/\\text{kg}^2",
    keywords: "gravitational constant newton" },
  { id: "g_earth", category: "constants", name: "Standard gravity g",
    latex: "g = 9.81\\,\\text{m/s}^2",
    keywords: "gravity earth" },
  { id: "e_charge", category: "constants", name: "Elementary charge e",
    latex: "e = 1.602 \\times 10^{-19}\\,\\text{C}",
    keywords: "elementary charge electron" },
  { id: "eps0", category: "constants", name: "Vacuum permittivity ε₀",
    latex: "\\varepsilon_0 = 8.854 \\times 10^{-12}\\,\\text{F/m}",
    keywords: "permittivity vacuum epsilon" },
  { id: "mu0", category: "constants", name: "Vacuum permeability μ₀",
    latex: "\\mu_0 = 4\\pi \\times 10^{-7}\\,\\text{T}\\!\\cdot\\!\\text{m/A}",
    keywords: "permeability vacuum mu" },
  { id: "m_e", category: "constants", name: "Electron mass",
    latex: "m_e = 9.109 \\times 10^{-31}\\,\\text{kg}",
    keywords: "electron mass" },
  { id: "m_p", category: "constants", name: "Proton mass",
    latex: "m_p = 1.673 \\times 10^{-27}\\,\\text{kg}",
    keywords: "proton mass" },
  { id: "rydberg", category: "constants", name: "Rydberg constant R∞",
    latex: "R_\\infty = 1.097 \\times 10^{7}\\,\\text{m}^{-1}",
    keywords: "rydberg constant" },
  { id: "stefan_const", category: "constants", name: "Stefan–Boltzmann σ",
    latex: "\\sigma = 5.670 \\times 10^{-8}\\,\\text{W/(m}^2\\text{K}^4)",
    keywords: "stefan boltzmann constant" },
  { id: "atm", category: "constants", name: "Atmospheric pressure",
    latex: "P_{\\text{atm}} = 1.013 \\times 10^{5}\\,\\text{Pa}",
    keywords: "atmospheric pressure" },
];

// Heuristic level assignment — picks beginner/intermediate/advanced based on
// category and name patterns. Tweak rules here rather than tagging 300 entries
// by hand; override any entry by setting `level` explicitly on that entry.
(function assignLevels() {
  const BEGINNER = new Set([
    // School-level staples across categories
    "pythag","dist","midpt","slope","line_pt_slope","line_si","tri_area_base",
    "trap_area","circle_area","circle_circ","sphere_vol","sphere_sa","cyl_vol",
    "cyl_sa","cone_vol","cone_sa","pyramid_vol","circle_eq","parabola_eq",
    "diffsqr","qform","discriminant","arith_sum","sum_n","geom_series_finite",
    "pyth_id","sinsum","cossum","law_cosines","law_sines","tri_area","deg_rad",
    "arc_length","mean","variance","stddev","normal_pdf","perm","comb",
    "newton2","kin_v","kin_s","kin_v2","kin_s_avg","momentum","ke","pe_grav",
    "hooke","work","power","ohm","power_elec","ideal_gas","heat_q","wave_speed",
    "snell","lens_eq","magnification","ph","poh","ph_poh","neutralisation",
    "comb_methane","photosyn","respiration","molarity","stress","strain",
    "c_light","g_earth","atm","logprod","logquot","logpow","expsum","binom_coef",
    "sum_to_prod","prod_to_sum","polar_xy","cart_polar","binomial",
    "doubsin","doubcos","doubtan","halfsin","halfcos","tansum",
    "bayes","cond_prob","exp_val","zscore","binomial_pmf","poisson_pmf",
    "geom_pmf","exp_pdf","uniform_pdf","linreg","ellipse_eq","hyperbola_eq",
    "heron","pyth_id2","pyth_id3","haber","water_diss","ph_poh","kw",
    "absineq","impulse","pe_spring","centripetal_f","centripetal_acc",
    // Newly-added chemistry beginner tier
    "boyle","charles","gay_lussac","combined_gas","latent_heat",
    "mass_percent","dilution","ethanol_combustion","iron_rust","acid_carbonate",
  ]);
  const ADVANCED = new Set([
    // Vector calculus & heavyweight theorems
    "stokes","divthm","green","laplacian","curl","divergence","gradient",
    "ibp","usub","taylor","maclaurin","ts_exp","ts_sin","ts_cos","ts_geom",
    "ts_ln","lhopital",
    // Linear algebra deep dives
    "svd","rank_nullity","char_poly","cramer","outer","matnorm","trace",
    "eigeneq","det3","inv2",
    // Stats advanced
    "covariance","correlation","lse_slope","ci_mean","tstat","chisq","stderr","var_def",
    // Physics advanced
    "I_disk","I_sphere","I_rod_mid","ang_mom","rot_ke","univ_grav","esc_v",
    "orb_v","kepler3","torque","pendulum_T","spring_T",
    "gauss_e_int","gauss_e_diff","gauss_b_diff","faraday_diff","ampere_max_diff",
    "lorentz_force","biot_savart","poynting","em_wave_speed","cap_energy",
    "ind_energy","rc_tau","rl_tau","lc_freq","cap_parallel_plate",
    "first_law","second_law","entropy_change","carnot_eta","stefan_boltz",
    "wien","boltz_dist","max_boltz_v","U_ideal","enthalpy","gibbs","delta_g_rxn",
    "fourier_heat",
    // Quantum / relativity — entire categories
    "schrod_td","schrod_ti","ham_kin","p_op","x_op","commutator","uncertainty",
    "planck_einstein","de_broglie","hydrogen_E","pib_E","ho_E","psi_prob",
    "expect","spin_pauli_z",
    "lorentz_t","lorentz_x","gamma_factor","time_dilate","len_contract",
    "rel_p","rel_E","mc2","energy_momentum","vel_add","schwarz_r",
    // Optics advanced
    "wave_eq","young_double","diffraction","bragg","doppler","intensity_inv_sq",
    // Chemistry advanced
    "kc","rate_law","arrhenius","beer_lambert","henderson","michaelis","nernst",
    "raoult","freezing_pt","boiling_pt","gibbs_eq","molality",
    // Discrete advanced
    "fermat_little","euler_thm","totient","gcd_id","modinv","stirling",
    "fib_closed","harmonic","master_thm","primecount",
    "incl_excl",
    // Engineering
    "bernoulli_eq","continuity","reynolds","drag","fourier_t","laplace_t",
    "convolution","rc_charge","youngs","shear_mod","bulk_mod","poisson",
    // Complex numbers
    "complex_conj","euler_id","euler_form","demoivre",
    // Cauchy
    "cauchy_schwarz","amgm",
    // Advanced algebra
    "sumcube","diffcube","sum_squares","sum_cubes","geom_series_inf",
    "logchange",
    // Advanced constants
    "hbar","k_b","n_a","R_gas","G_grav","e_charge","eps0","mu0","m_e","m_p",
    "rydberg","stefan_const","h_planck",
    // Newly-added advanced chemistry
    "vdw","gibbs_non_std","vant_hoff_eq","rate_1st_int","rate_2nd_int","rate_0_int",
    "entropy_universe","delta_g_nf","rydberg_formula","bohr_radius",
  ]);
  for (const f of window.FORMULAS) {
    if (f.level) continue;
    if (BEGINNER.has(f.id))  { f.level = "beginner";     continue; }
    if (ADVANCED.has(f.id))  { f.level = "advanced";     continue; }
    f.level = "intermediate";
  }
})();

// Heuristic syllabus tagging — assigns each formula to the UK exam boards / IB
// syllabuses where it commonly appears. Combines category + level. Specific
// entries can override by setting `syllabuses: [...]` directly on the entry.
//
//   gcse-maths · gcse-physics · gcse-chemistry
//   alevel-maths · alevel-further-maths · alevel-physics · alevel-chemistry
//   ib-maths · ib-physics · ib-chemistry
const MATHS_CATS    = new Set(["algebra","trig","calculus","linalg","geometry","stats","discrete","engineering"]);
const PHYSICS_CATS  = new Set(["mechanics","em","thermo","quantum","relativity","optics"]);

(function assignSyllabuses() {
  for (const f of window.FORMULAS) {
    if (f.syllabuses) continue;
    const s = new Set();
    const lvl = f.level || "intermediate";
    if (MATHS_CATS.has(f.category)) {
      if (lvl === "beginner")     s.add("gcse-maths");
      if (lvl === "intermediate") { s.add("alevel-maths"); s.add("ib-maths"); }
      if (lvl === "advanced")     { s.add("alevel-further-maths"); s.add("ib-maths"); }
    }
    if (PHYSICS_CATS.has(f.category)) {
      if (lvl === "beginner")     { s.add("gcse-physics"); s.add("alevel-physics"); }
      if (lvl === "intermediate") { s.add("alevel-physics"); s.add("ib-physics"); }
      if (lvl === "advanced") {
        // Quantum and relativity at the advanced level (Schrödinger, Lorentz)
        // are university material, not A-Level Physics. Tag them to IB only.
        if (f.category === "quantum" || f.category === "relativity") {
          s.add("ib-physics");
        } else {
          s.add("alevel-physics");
          s.add("ib-physics");
        }
        // Mechanics + EM at this level are calc-heavy → also bridge to Further Maths
        if (f.category === "mechanics" || f.category === "em") {
          s.add("alevel-further-maths");
        }
      }
    }
    if (f.category === "chemistry") {
      if (lvl === "beginner")     { s.add("gcse-chemistry"); s.add("alevel-chemistry"); }
      if (lvl === "intermediate") { s.add("alevel-chemistry"); s.add("ib-chemistry"); }
      if (lvl === "advanced")     { s.add("alevel-chemistry"); s.add("ib-chemistry"); }
    }
    if (f.category === "constants") {
      // Constants used across multiple sciences
      s.add("alevel-physics"); s.add("alevel-chemistry");
      s.add("ib-physics"); s.add("ib-chemistry");
      if (lvl === "beginner") { s.add("gcse-physics"); s.add("gcse-chemistry"); }
    }
    f.syllabuses = [...s];
  }
})();

// Filter helper — accepts either a level (beginner/intermediate/advanced/all)
// or a syllabus id. Levels show everything UP TO the picked level (cumulative);
// syllabus ids show only formulas tagged with that exact syllabus.
window.filterByLevel = function(formulas, scope) {
  if (!scope || scope === "all") return formulas;
  if (["beginner","intermediate","advanced"].includes(scope)) {
    const rank = { beginner: 0, intermediate: 1, advanced: 2 };
    const max = rank[scope];
    return formulas.filter(f => rank[f.level || "intermediate"] <= max);
  }
  // Syllabus filter — exact membership
  return formulas.filter(f => Array.isArray(f.syllabuses) && f.syllabuses.includes(scope));
};
