// Auto-generated by scripts/gen-all-locales.mjs: the interface languages with a real
// translation (English copies are not offered; D3). Braille tables are chosen separately.
export const ALL_SUPPORTED_LOCALES = [
  {
    "code": "afr",
    "lang": "af",
    "name": "Afrikaans",
    "nativeName": "Afrikaans",
    "dir": "ltr",
    "defaultBraille": "afr-za-g2",
    "translated": true
  },
  {
    "code": "ar",
    "lang": "ar",
    "name": "Arabic",
    "nativeName": "العربية",
    "dir": "rtl",
    "defaultBraille": "ar-ar-g2",
    "translated": true
  },
  {
    "code": "as",
    "lang": "as",
    "name": "Assamese",
    "nativeName": "অসমীয়া",
    "dir": "ltr",
    "defaultBraille": "as-in-g1",
    "translated": true
  },
  {
    "code": "be",
    "lang": "bn-IN",
    "name": "Bengali (India)",
    "nativeName": "বাংলা",
    "dir": "ltr",
    "defaultBraille": "be-in-g1",
    "translated": true
  },
  {
    "code": "bel",
    "lang": "be",
    "name": "Belarusian",
    "nativeName": "Беларуская",
    "dir": "ltr",
    "defaultBraille": "bel",
    "translated": true
  },
  {
    "code": "bg",
    "lang": "bg",
    "name": "Bulgarian",
    "nativeName": "Български",
    "dir": "ltr",
    "defaultBraille": "bg",
    "translated": true
  },
  {
    "code": "bh",
    "lang": "bho",
    "name": "Bihari",
    "nativeName": "भोजपुरी",
    "dir": "ltr",
    "defaultBraille": "bh",
    "translated": true
  },
  {
    "code": "ca",
    "lang": "ca",
    "name": "Catalan",
    "nativeName": "Català",
    "dir": "ltr",
    "defaultBraille": "ca-g1",
    "translated": true
  },
  {
    "code": "ckb",
    "lang": "ckb",
    "name": "Central Kurdish (Sorani)",
    "nativeName": "کوردیی ناوەندی",
    "dir": "rtl",
    "defaultBraille": "ckb-g1",
    "translated": true
  },
  {
    "code": "cs",
    "lang": "cs",
    "name": "Czech",
    "nativeName": "Čeština",
    "dir": "ltr",
    "defaultBraille": "cs-g1",
    "translated": true
  },
  {
    "code": "cy",
    "lang": "cy",
    "name": "Welsh",
    "nativeName": "Cymraeg",
    "dir": "ltr",
    "defaultBraille": "cy-cy-g2",
    "translated": true
  },
  {
    "code": "da",
    "lang": "da",
    "name": "Danish",
    "nativeName": "Dansk",
    "dir": "ltr",
    "defaultBraille": "da-dk-g26",
    "translated": true
  },
  {
    "code": "de",
    "lang": "de",
    "name": "German",
    "nativeName": "Deutsch",
    "dir": "ltr",
    "defaultBraille": "de-g2",
    "translated": true
  },
  {
    "code": "el",
    "lang": "el",
    "name": "Greek",
    "nativeName": "Ελληνικά",
    "dir": "ltr",
    "defaultBraille": "el",
    "translated": true
  },
  {
    "code": "en",
    "lang": "en",
    "name": "English",
    "nativeName": "English",
    "dir": "ltr",
    "defaultBraille": "en-ueb-g1",
    "translated": true
  },
  {
    "code": "eo",
    "lang": "eo",
    "name": "Esperanto",
    "nativeName": "Esperanto",
    "dir": "ltr",
    "defaultBraille": "eo-g1",
    "translated": true
  },
  {
    "code": "es",
    "lang": "es",
    "name": "Spanish",
    "nativeName": "Español",
    "dir": "ltr",
    "defaultBraille": "es-g1",
    "translated": true
  },
  {
    "code": "et",
    "lang": "et",
    "name": "Estonian",
    "nativeName": "Eesti",
    "dir": "ltr",
    "defaultBraille": "et-g0",
    "translated": true
  },
  {
    "code": "fa",
    "lang": "fa",
    "name": "Persian",
    "nativeName": "فارسی",
    "dir": "rtl",
    "defaultBraille": "fa-ir-g1",
    "translated": true
  },
  {
    "code": "fi",
    "lang": "fi",
    "name": "Finnish",
    "nativeName": "Suomi",
    "dir": "ltr",
    "defaultBraille": "fi",
    "translated": true
  },
  {
    "code": "fil",
    "lang": "fil",
    "name": "Filipino",
    "nativeName": "Filipino",
    "dir": "ltr",
    "defaultBraille": "fil-g2",
    "translated": true
  },
  {
    "code": "fr",
    "lang": "fr",
    "name": "French",
    "nativeName": "Français",
    "dir": "ltr",
    "defaultBraille": "fr-bfu-comp6",
    "translated": true
  },
  {
    "code": "ga",
    "lang": "ga",
    "name": "Irish",
    "nativeName": "Gaeilge",
    "dir": "ltr",
    "defaultBraille": "ga-g2",
    "translated": true
  },
  {
    "code": "gd",
    "lang": "gd",
    "name": "Scottish Gaelic",
    "nativeName": "Gàidhlig",
    "dir": "ltr",
    "defaultBraille": "gd",
    "translated": true
  },
  {
    "code": "gu",
    "lang": "gu",
    "name": "Gujarati",
    "nativeName": "ગુજરાતી",
    "dir": "ltr",
    "defaultBraille": "gu-in-g1",
    "translated": true
  },
  {
    "code": "he",
    "lang": "he",
    "name": "Hebrew",
    "nativeName": "עברית",
    "dir": "rtl",
    "defaultBraille": "he-IL",
    "translated": true
  },
  {
    "code": "hi",
    "lang": "hi",
    "name": "Hindi",
    "nativeName": "हिन्दी",
    "dir": "ltr",
    "defaultBraille": "hi-in-g1",
    "translated": true
  },
  {
    "code": "hr",
    "lang": "hr",
    "name": "Croatian",
    "nativeName": "Hrvatski",
    "dir": "ltr",
    "defaultBraille": "hr-g1",
    "translated": true
  },
  {
    "code": "hu",
    "lang": "hu",
    "name": "Hungarian",
    "nativeName": "Magyar",
    "dir": "ltr",
    "defaultBraille": "hu-hu-g2",
    "translated": true
  },
  {
    "code": "hy",
    "lang": "hy",
    "name": "Armenian",
    "nativeName": "Հայերեն",
    "dir": "ltr",
    "defaultBraille": "hy",
    "translated": true
  },
  {
    "code": "is",
    "lang": "is",
    "name": "Icelandic",
    "nativeName": "Íslenska",
    "dir": "ltr",
    "defaultBraille": "is",
    "translated": true
  },
  {
    "code": "it",
    "lang": "it",
    "name": "Italian",
    "nativeName": "Italiano",
    "dir": "ltr",
    "defaultBraille": "it-it-comp6",
    "translated": true
  },
  {
    "code": "ja",
    "lang": "ja",
    "name": "Japanese",
    "nativeName": "日本語",
    "dir": "ltr",
    "defaultBraille": "ja-kantenji",
    "translated": true
  },
  {
    "code": "ka",
    "lang": "ka",
    "name": "Georgian",
    "nativeName": "Ქართული",
    "dir": "ltr",
    "defaultBraille": "ka",
    "translated": true
  },
  {
    "code": "kk",
    "lang": "kk",
    "name": "Kazakh",
    "nativeName": "Қазақша",
    "dir": "ltr",
    "defaultBraille": "kk",
    "translated": true
  },
  {
    "code": "km",
    "lang": "km",
    "name": "Khmer",
    "nativeName": "ភាសាខ្មែរ",
    "dir": "ltr",
    "defaultBraille": "km-g1",
    "translated": true
  },
  {
    "code": "ko",
    "lang": "ko",
    "name": "Korean",
    "nativeName": "한국어",
    "dir": "ltr",
    "defaultBraille": "ko-g2",
    "translated": true
  },
  {
    "code": "kok",
    "lang": "kok",
    "name": "Konkani",
    "nativeName": "कोंकणी",
    "dir": "ltr",
    "defaultBraille": "kok",
    "translated": true
  },
  {
    "code": "lg",
    "lang": "lg",
    "name": "Luganda",
    "nativeName": "Luganda",
    "dir": "ltr",
    "defaultBraille": "lg-ug-g1",
    "translated": true
  },
  {
    "code": "lo",
    "lang": "lo",
    "name": "Lao",
    "nativeName": "ລາວ",
    "dir": "ltr",
    "defaultBraille": "lo-g1",
    "translated": true
  },
  {
    "code": "lt",
    "lang": "lt",
    "name": "Lithuanian",
    "nativeName": "Lietuvių",
    "dir": "ltr",
    "defaultBraille": "lt",
    "translated": true
  },
  {
    "code": "lv",
    "lang": "lv",
    "name": "Latvian",
    "nativeName": "Latviešu",
    "dir": "ltr",
    "defaultBraille": "Lv-Lv-g1",
    "translated": true
  },
  {
    "code": "mao",
    "lang": "mi",
    "name": "Maori",
    "nativeName": "Te Reo Māori",
    "dir": "ltr",
    "defaultBraille": "mao-nz-g1",
    "translated": true
  },
  {
    "code": "mk",
    "lang": "mk",
    "name": "Macedonian",
    "nativeName": "Македонски",
    "dir": "ltr",
    "defaultBraille": "mk-g1",
    "translated": true
  },
  {
    "code": "ml",
    "lang": "ml",
    "name": "Malayalam",
    "nativeName": "മലയാളം",
    "dir": "ltr",
    "defaultBraille": "ml-in-g1",
    "translated": true
  },
  {
    "code": "mn",
    "lang": "mn",
    "name": "Mongolian",
    "nativeName": "Монгол",
    "dir": "ltr",
    "defaultBraille": "mn-MN-g2",
    "translated": true
  },
  {
    "code": "mr",
    "lang": "mr",
    "name": "Marathi",
    "nativeName": "मराठी",
    "dir": "ltr",
    "defaultBraille": "mr-in-g1",
    "translated": true
  },
  {
    "code": "ms",
    "lang": "ms",
    "name": "Malay",
    "nativeName": "Bahasa Melayu",
    "dir": "ltr",
    "defaultBraille": "ms-my-g2",
    "translated": true
  },
  {
    "code": "my",
    "lang": "my",
    "name": "Burmese",
    "nativeName": "မြန်မာစာ",
    "dir": "ltr",
    "defaultBraille": "my-g2",
    "translated": true
  },
  {
    "code": "ne",
    "lang": "ne",
    "name": "Nepali",
    "nativeName": "नेपाली",
    "dir": "ltr",
    "defaultBraille": "ne",
    "translated": true
  },
  {
    "code": "no",
    "lang": "nb",
    "name": "Norwegian",
    "nativeName": "Norsk",
    "dir": "ltr",
    "defaultBraille": "no-no-g2",
    "translated": true
  },
  {
    "code": "ny",
    "lang": "ny",
    "name": "Chichewa",
    "nativeName": "Chichewa",
    "dir": "ltr",
    "defaultBraille": "ny-mw",
    "translated": true
  },
  {
    "code": "or",
    "lang": "or",
    "name": "Odia",
    "nativeName": "ଓଡ଼ିଆ",
    "dir": "ltr",
    "defaultBraille": "or-in-g1",
    "translated": true
  },
  {
    "code": "pl",
    "lang": "pl",
    "name": "Polish",
    "nativeName": "Polski",
    "dir": "ltr",
    "defaultBraille": "Pl-Pl-g1",
    "translated": true
  },
  {
    "code": "pt",
    "lang": "pt-BR",
    "name": "Portuguese",
    "nativeName": "Português",
    "dir": "ltr",
    "defaultBraille": "pt-pt-g2",
    "translated": true
  },
  {
    "code": "pu",
    "lang": "pa-IN",
    "name": "Punjabi (India)",
    "nativeName": "ਪੰਜਾਬੀ",
    "dir": "ltr",
    "defaultBraille": "pu-in-g1",
    "translated": true
  },
  {
    "code": "ro",
    "lang": "ro",
    "name": "Romanian",
    "nativeName": "Română",
    "dir": "ltr",
    "defaultBraille": "ro",
    "translated": true
  },
  {
    "code": "ru",
    "lang": "ru",
    "name": "Russian",
    "nativeName": "Русский",
    "dir": "ltr",
    "defaultBraille": "ru-comp6",
    "translated": true
  },
  {
    "code": "rw",
    "lang": "rw",
    "name": "Kinyarwanda",
    "nativeName": "Ikinyarwanda",
    "dir": "ltr",
    "defaultBraille": "rw-rw-g1",
    "translated": true
  },
  {
    "code": "sin",
    "lang": "si",
    "name": "Sinhala",
    "nativeName": "සිංහල",
    "dir": "ltr",
    "defaultBraille": "sin",
    "translated": true
  },
  {
    "code": "sk",
    "lang": "sk",
    "name": "Slovak",
    "nativeName": "Slovenčina",
    "dir": "ltr",
    "defaultBraille": "sk-g1",
    "translated": true
  },
  {
    "code": "sl",
    "lang": "sl",
    "name": "Slovenian",
    "nativeName": "Slovenščina",
    "dir": "ltr",
    "defaultBraille": "sl-si-g1",
    "translated": true
  },
  {
    "code": "sot",
    "lang": "st",
    "name": "Southern Sotho",
    "nativeName": "Sesotho",
    "dir": "ltr",
    "defaultBraille": "sot-za-g2",
    "translated": true
  },
  {
    "code": "sr",
    "lang": "sr",
    "name": "Serbian",
    "nativeName": "Српски",
    "dir": "ltr",
    "defaultBraille": "sr-g1",
    "translated": true
  },
  {
    "code": "sv",
    "lang": "sv",
    "name": "Swedish",
    "nativeName": "Svenska",
    "dir": "ltr",
    "defaultBraille": "sv-g2",
    "translated": true
  },
  {
    "code": "sw",
    "lang": "sw",
    "name": "Swahili",
    "nativeName": "Kiswahili",
    "dir": "ltr",
    "defaultBraille": "sw-ke-g2",
    "translated": true
  },
  {
    "code": "ta",
    "lang": "ta",
    "name": "Tamil",
    "nativeName": "தமிழ்",
    "dir": "ltr",
    "defaultBraille": "ta",
    "translated": true
  },
  {
    "code": "te",
    "lang": "te",
    "name": "Telugu",
    "nativeName": "తెలుగు",
    "dir": "ltr",
    "defaultBraille": "te-in-g1",
    "translated": true
  },
  {
    "code": "th",
    "lang": "th",
    "name": "Thai",
    "nativeName": "ไทย",
    "dir": "ltr",
    "defaultBraille": "th-g2",
    "translated": true
  },
  {
    "code": "tr",
    "lang": "tr",
    "name": "Turkish",
    "nativeName": "Türkçe",
    "dir": "ltr",
    "defaultBraille": "tr-g2",
    "translated": true
  },
  {
    "code": "tt",
    "lang": "tt",
    "name": "Tatar",
    "nativeName": "Татарча",
    "dir": "ltr",
    "defaultBraille": "tt",
    "translated": true
  },
  {
    "code": "uk",
    "lang": "uk",
    "name": "Ukrainian",
    "nativeName": "Українська",
    "dir": "ltr",
    "defaultBraille": "uk",
    "translated": true
  },
  {
    "code": "ur",
    "lang": "ur",
    "name": "Urdu",
    "nativeName": "اردو",
    "dir": "rtl",
    "defaultBraille": "ur-pk-g2",
    "translated": true
  },
  {
    "code": "uz",
    "lang": "uz",
    "name": "Uzbek",
    "nativeName": "Oʻzbekcha",
    "dir": "ltr",
    "defaultBraille": "uz-g1",
    "translated": true
  },
  {
    "code": "vi",
    "lang": "vi",
    "name": "Vietnamese",
    "nativeName": "Tiếng Việt",
    "dir": "ltr",
    "defaultBraille": "vi-vn-g2",
    "translated": true
  },
  {
    "code": "yi",
    "lang": "yi",
    "name": "Yiddish",
    "nativeName": "ייִדיש",
    "dir": "rtl",
    "defaultBraille": "yi",
    "translated": true
  },
  {
    "code": "zh",
    "lang": "zh-Hant",
    "name": "Chinese (Traditional)",
    "nativeName": "中文 (繁體)",
    "dir": "ltr",
    "defaultBraille": "zh-hk",
    "translated": true
  },
  {
    "code": "zhc",
    "lang": "zh-Hans",
    "name": "Chinese (Simplified)",
    "nativeName": "中文 (简体)",
    "dir": "ltr",
    "defaultBraille": "zhcn-g2",
    "translated": true
  }
];
